version: "3.7"
services:

  web:
    image: nginx:alpine
    volumes:
      - "./public:/var/www/html"
      - "./docker/dev.nginx:/etc/nginx/conf.d/default.conf"
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:80"

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - "./public:/var/www/html"
      - "./docker/php/php.ini-development:/usr/local/etc/php/php.ini"
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
    expose:
      - "9000"

  db:
    image: mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${OC_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${OC_DB_DATABASE}
      MYSQL_USER: ${OC_DB_USERNAME}
      MYSQL_PASSWORD: ${OC_DB_PASSWORD}
    ports:
      - "3306:3306"